# Generated by Django 5.2 on 2025-04-11 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAPIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('endpoint', models.CharField(max_length=255, verbose_name='نقطه پایانی API')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='پارامترهای درخواست')),
                ('resource_type', models.CharField(max_length=50, verbose_name='نوع منبع')),
                ('resource_count', models.IntegerField(default=1, verbose_name='تعداد منبع')),
                ('credits_used', models.FloatField(verbose_name='اعتبار مصرف شده')),
                ('cost_usd', models.FloatField(verbose_name='هزینه (دلار)')),
                ('response_time_ms', models.IntegerField(verbose_name='زمان پاسخ (میلی\u200cثانیه)')),
                ('status_code', models.IntegerField(verbose_name='کد وضعیت')),
                ('success', models.BooleanField(default=True, verbose_name='موفقیت')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='برداشت از کش')),
            ],
            options={
                'verbose_name': 'درخواست TwitterAPI',
                'verbose_name_plural': 'درخواست\u200cهای TwitterAPI',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TwitterAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='تاریخ')),
                ('request_count', models.IntegerField(default=0, verbose_name='تعداد درخواست\u200cها')),
                ('credits_used', models.FloatField(default=0, verbose_name='اعتبار مصرف شده')),
                ('cost_usd', models.FloatField(default=0, verbose_name='هزینه (دلار)')),
                ('tweet_count', models.IntegerField(default=0, verbose_name='تعداد توییت\u200cهای دریافتی')),
                ('user_count', models.IntegerField(default=0, verbose_name='تعداد کاربران دریافتی')),
                ('follower_count', models.IntegerField(default=0, verbose_name='تعداد دنبال\u200cکنندگان دریافتی')),
                ('cache_hits', models.IntegerField(default=0, verbose_name='تعداد موفقیت کش')),
                ('cache_misses', models.IntegerField(default=0, verbose_name='تعداد عدم موفقیت کش')),
                ('endpoint_stats', models.JSONField(blank=True, default=dict, verbose_name='آمار به تفکیک endpoint')),
            ],
            options={
                'verbose_name': 'آمار مصرف TwitterAPI',
                'verbose_name_plural': 'آمار مصرف TwitterAPI',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TwitterAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100, verbose_name='کلید API')),
                ('daily_budget_usd', models.FloatField(default=0.5, verbose_name='بودجه روزانه (دلار)')),
                ('enable_cache', models.BooleanField(default=True, verbose_name='فعال\u200cسازی کش')),
                ('cache_dir', models.CharField(default='.twitter_cache', max_length=255, verbose_name='مسیر کش')),
                ('max_requests_per_minute', models.IntegerField(default=30, verbose_name='حداکثر درخواست در دقیقه')),
                ('base_delay', models.FloatField(default=1.0, verbose_name='تأخیر پایه بین درخواست\u200cها (ثانیه)')),
                ('default_max_pages', models.IntegerField(default=1, verbose_name='محدودیت پیش\u200cفرض تعداد صفحات')),
                ('default_max_results', models.IntegerField(default=50, verbose_name='محدودیت پیش\u200cفرض تعداد نتایج')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twitter_api_settings', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات TwitterAPI',
                'verbose_name_plural': 'تنظیمات TwitterAPI',
            },
        ),
    ]
