# Generated by Django 5.2 on 2025-04-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('result_type', models.CharField(choices=[('recent', 'Recent'), ('popular', 'Popular'), ('mixed', 'Mixed')], default='recent', max_length=20)),
                ('language', models.CharField(default='fa', max_length=10)),
                ('count_per_run', models.IntegerField(default=100)),
                ('schedule_interval', models.IntegerField(default=60)),
                ('total_collected', models.IntegerField(default=0)),
                ('total_valid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('tweet_count', models.IntegerField(default=0)),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('influence_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Twitter User',
                'verbose_name_plural': 'Twitter Users',
                'indexes': [models.Index(fields=['username'], name='collector_t_usernam_1007c0_idx'), models.Index(fields=['influence_score'], name='collector_t_influen_7cb9cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='fa', max_length=10)),
                ('reply_count', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('quote_count', models.IntegerField(default=0)),
                ('replied_to_tweet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('retweeted_tweet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quoted_tweet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('importance_score', models.FloatField(default=0.0)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='collector.twitteruser')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'indexes': [models.Index(fields=['created_at'], name='collector_t_created_fd26f6_idx'), models.Index(fields=['importance_score'], name='collector_t_importa_949079_idx'), models.Index(fields=['engagement_score'], name='collector_t_engagem_c9b9e0_idx')],
            },
        ),
    ]
