# Generated by Django 5.2 on 2025-04-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='priority',
            field=models.CharField(choices=[('high', 'اولویت بالا'), ('medium', 'اولویت متوسط'), ('low', 'اولویت پایین')], default='medium', max_length=10),
        ),
    ]
