# Generated by Django 5.1.8 on 2025-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together={('task_id', 'query')},
        ),
    ]
