# Generated by Django 5.1.8 on 2025-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_alter_tasklog_task_id_alter_tasklog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='archive_until_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='last_tweet_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_id',
            field=models.CharField(max_length=150),
        ),
    ]
