# Generated by Django 5.2 on 2025-04-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_initial'),
        ('memory', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pattern_type', models.CharField(choices=[('sentiment_trend', 'Sentiment Trend'), ('topic_trend', 'Topic Trend'), ('user_activity', 'User Activity'), ('user_relationship', 'User Relationship'), ('emerging_topic', 'Emerging Topic'), ('news_correlation', 'News Correlation'), ('unusual_activity', 'Unusual Activity')], max_length=50)),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=50)),
                ('news_articles', models.ManyToManyField(blank=True, related_name='patterns', to='news.newsarticle')),
                ('topics', models.ManyToManyField(related_name='patterns', to='memory.topic')),
                ('tweets', models.ManyToManyField(blank=True, related_name='patterns', to='collector.tweet')),
                ('users', models.ManyToManyField(blank=True, related_name='patterns', to='collector.twitteruser')),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'indexes': [models.Index(fields=['pattern_type'], name='analyzer_pa_pattern_5da3d4_idx'), models.Index(fields=['confidence'], name='analyzer_pa_confide_b7931b_idx'), models.Index(fields=['detected_at'], name='analyzer_pa_detecte_7eaa08_idx'), models.Index(fields=['start_date', 'end_date'], name='analyzer_pa_start_d_4b8735_idx')],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=20)),
                ('confidence', models.FloatField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=50)),
                ('news_article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='news.newsarticle')),
                ('tweet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='collector.tweet')),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'indexes': [models.Index(fields=['sentiment'], name='analyzer_se_sentime_7cd0c6_idx'), models.Index(fields=['confidence'], name='analyzer_se_confide_479351_idx'), models.Index(fields=['analyzed_at'], name='analyzer_se_analyze_7ec9d9_idx')],
            },
        ),
    ]
